name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - '**/*.go'
      - '!tools/**/*'
  pull_request:
    branches:
      - main
    paths:
      - '**/*.go'
      - '!tools/**/*'
  release:
    types:
      - created

jobs:
  build-and-deploy:
    runs-on: ${{ matrix.platform }}

    strategy:
      matrix:
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        go-version:
          - 1.19

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build for ${{ matrix.platform }}
        run: |
          go build -o analyze-tags

      - name: Test
        run: echo "No tests to run."

      - name: Create Zip Archive (Windows)
        if: ${{ matrix.platform == 'windows-latest' }}
        run: |
          Rename-Item -Path ./analyze-tags -NewName "analyze-tags.exe"
          powershell Compress-Archive -Path ./analyze-tags.exe -DestinationPath analyze-tags-${{ matrix.platform }}.zip

      - name: Create Zip Archive (Linux, macOS)
        if: ${{ matrix.platform != 'windows-latest' }}
        run: |
          zip -r analyze-tags-${{ matrix.platform }}.zip analyze-tags

      - name: Upload Assets
        if: ${{ github.event_name == 'release' }}
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./analyze-tags-${{ matrix.platform }}.zip
          asset_name: analyze-tags-${{ matrix.platform }}.zip
          asset_content_type: application/octet-stream